name=AFE_NXP_Arduino
version=2.0.0
author=Tedd OKANO
maintainer=Tedd OKANO
sentence=Class library for NXP Analog Front End
paragraph=NAFE13388, NAFE73388, NAFE13388-UIM, NAFExx388-EVB, NAFE33352, NAFE93352, NAFE33352-UIOM and NAFE33352-EVB are supported
category=Device Control
url=https://github.com/teddokano/AFE_NXP_Arduino
architectures=*
depends=
