AFE_NXP_Arduino: NAFE13388_Base Class Reference
NAFE13388_Base Class Reference
#include <AFE_NXP.h>
Public Member Functions
NAFE13388_Base ()
virtual ~NAFE13388_Base ()
virtual void begin (void)
virtual void boot (void)
virtual void reset (void)
virtual void board_init (int _pin_nINT, int _pin_DRDY, int _pin_SYN, int _pin_nRESET)
virtual void logical_ch_config (int ch, uint16_t cc0, uint16_t cc1, uint16_t cc2, uint16_t cc3)
virtual double read (int ch)
Public Member Functions inherited from SPI_for_AFE
void txrx (uint8_t *data, int size)
void write_r16 (uint16_t reg)
void write_r16 (uint16_t reg, uint16_t val)
uint16_t read_r16 (uint16_t reg)
void write_r24 (uint16_t reg, uint32_t val)
int32_t read_r24 (uint16_t reg)
Public Attributes
int enabled_channels
double coeff_uV [16]
Detailed Description
Definition at line 22 of file AFE_NXP.h.
Constructor & Destructor Documentation
NAFE13388_Base()
NAFE13388_Base::NAFE13388_Base ()
Constructor to create a NAFE13388 instance
Definition at line 5 of file AFE_NXP.cpp.
~NAFE13388_Base()
NAFE13388_Base::~NAFE13388_Base () virtual
Destractor
Definition at line 9 of file AFE_NXP.cpp.
Member Function Documentation
begin()
void NAFE13388_Base::begin (void) virtual
Begin the device operation
NAFE13388 initialization. It does following steps (1) Set pins 2 and 3 are input for nINT and nDRDY (2) Set pins 5 and 6 are output and fixed to HIGH for ADC_SYN and ADC_nRESET (3) Call reset() (4) Call boot()
Definition at line 13 of file AFE_NXP.cpp.
board_init()
void NAFE13388_Base::board_init (int _pin_nINT, int _pin_DRDY, int _pin_SYN, int _pin_nRESET) virtual
Board initialization (initializing control pin state)
Parameters
_pin_nINT pin number for nINT
_pin_DRDY pin number for DRDY
_pin_SYN pin number for SYN
_pin_nRESET pin number for nRESET
Definition at line 38 of file AFE_NXP.cpp.
Referenced by NAFE13388::NAFE13388(), and NAFE13388_UIM::NAFE13388_UIM().
boot()
void NAFE13388_Base::boot (void) virtual
Set system-level config registers
Definition at line 19 of file AFE_NXP.cpp.
Referenced by begin().
logical_ch_config()
void NAFE13388_Base::logical_ch_config (int ch, uint16_t cc0, uint16_t cc1, uint16_t cc2, uint16_t cc3) virtual
Configure logical channel
Parameters
ch logical channel number (0 ~ 15)
cc0 16bit value to be set CH_CONFIG0 register (0x20)
cc1 16bit value to be set CH_CONFIG1 register (0x21)
cc2 16bit value to be set CH_CONFIG2 register (0x22)
cc3 16bit value to be set CH_CONFIG3 register (0x23)
Definition at line 53 of file AFE_NXP.cpp.
read()
double NAFE13388_Base::read (int ch) virtual
Read ADC
Parameters
ch logical channel number (0 ~ 15)
Returns
ADC read value in micro-volt
Definition at line 78 of file AFE_NXP.cpp.
reset()
void NAFE13388_Base::reset (void) virtual
Issue RESET command
Definition at line 32 of file AFE_NXP.cpp.
Referenced by begin().
Member Data Documentation
coeff_uV
double NAFE13388_Base::coeff_uV[16]
Coefficient to convert from ADC read value to micro-volt
Definition at line 77 of file AFE_NXP.h.
Referenced by logical_ch_config(), and read().
enabled_channels
int NAFE13388_Base::enabled_channels
Number of enabled logical channels
Definition at line 74 of file AFE_NXP.h.
Referenced by logical_ch_config().
The documentation for this class was generated from the following files:
AFE_NXP.h
AFE_NXP.cpp